services:
  - type: web
    name: p2p-file-sharing
    env: node
    buildCommand: npm install && npm run build && ls -la && ls -la dist/
    startCommand: cd /opt/render/project && node dist/index.js
    publishPath: .
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
